### ISSUE TITLE
gitlab-ee 企业版自签许可证license | Mayer Shi

### ISSUE THREAD

**Issue by Mayershi** [Mayershi/mayershi.github.io#10]
https://www.mayershi.com/2019/12/23/crack-gitlab-ee-licence/ 

 本篇文章主要是研究gitlab-ee的licence签发方式，仅供大家学习参考使用。请尊重软件开发者成果，支持正版。

**Comment by lfire** [comment]
这个500的错误真不好查呀，大师有解决这个问题吗？

**Comment by Mayershi** [comment]
> @lfire
> 这个500的错误真不好查呀，大师有解决这个问题吗？
> 我没有细究这个问题，因为不影响使用也就放弃排查了。

**Comment by lfire** [comment]
OK,也确实是，谢谢！
